// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillsShowcase.Api.Models.Data;

#nullable disable

namespace SkillsShowcase.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240828192059_SeedDataSessionLogs")]
    partial class SeedDataSessionLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillsShowcase.Shared.Domain.Models.DcVillains", b =>
                {
                    b.Property<int>("DcVillanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DcVillanId"));

                    b.Property<string>("CityLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlacedInArkham")
                        .HasColumnType("int");

                    b.Property<int?>("SupermanLevelVillan")
                        .HasColumnType("int");

                    b.Property<int?>("ThreatLevel")
                        .HasColumnType("int");

                    b.Property<int?>("VillanAge")
                        .HasColumnType("int");

                    b.Property<string>("VillanName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VillanPower")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weaknesses")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DcVillanId");

                    b.ToTable("DcVillains");

                    b.HasData(
                        new
                        {
                            DcVillanId = 1,
                            CityLocation = "Gotham",
                            PlacedInArkham = 0,
                            ThreatLevel = 3,
                            VillanAge = 43,
                            VillanName = "Joker",
                            VillanPower = "None/Cunning",
                            Weaknesses = "None"
                        },
                        new
                        {
                            DcVillanId = 2,
                            CityLocation = "Apokolips",
                            PlacedInArkham = 2,
                            ThreatLevel = 4,
                            VillanAge = 1000,
                            VillanName = "Darkseid",
                            VillanPower = "SuperStrength/CosmicPowers",
                            Weaknesses = "None/Superman"
                        },
                        new
                        {
                            DcVillanId = 3,
                            CityLocation = "Metropolis",
                            PlacedInArkham = 0,
                            ThreatLevel = 2,
                            VillanAge = 44,
                            VillanName = "Lex Luthor",
                            VillanPower = "Genius Intellect",
                            Weaknesses = "None/Regular Human/Superman"
                        },
                        new
                        {
                            DcVillanId = 4,
                            CityLocation = "Gothom",
                            PlacedInArkham = 0,
                            ThreatLevel = 5,
                            VillanAge = 58,
                            VillanName = "DeathStroke",
                            VillanPower = "Enhanced Human",
                            Weaknesses = "None"
                        },
                        new
                        {
                            DcVillanId = 5,
                            CityLocation = "Gothom",
                            PlacedInArkham = 1,
                            ThreatLevel = 5,
                            VillanAge = 49,
                            VillanName = "Two-Face",
                            VillanPower = "None",
                            Weaknesses = "None"
                        },
                        new
                        {
                            DcVillanId = 6,
                            CityLocation = "Unknown",
                            PlacedInArkham = 2,
                            ThreatLevel = 4,
                            VillanAge = 1000,
                            VillanName = "Braniac",
                            VillanPower = "Genius Intellect/Cosmic Powers",
                            Weaknesses = "None/Superman"
                        },
                        new
                        {
                            DcVillanId = 7,
                            CityLocation = "Gothom",
                            PlacedInArkham = 0,
                            ThreatLevel = 5,
                            VillanAge = 37,
                            VillanName = "Riddler",
                            VillanPower = "None",
                            Weaknesses = "None"
                        },
                        new
                        {
                            DcVillanId = 8,
                            CityLocation = "Space",
                            PlacedInArkham = 0,
                            ThreatLevel = 2,
                            VillanAge = 59,
                            VillanName = "Sinestro",
                            VillanPower = "Yellow Lantern Ring",
                            Weaknesses = "Removal of Ring"
                        },
                        new
                        {
                            DcVillanId = 9,
                            CityLocation = "Unknown",
                            PlacedInArkham = 2,
                            ThreatLevel = 4,
                            VillanAge = 1000,
                            VillanName = "Doomsday",
                            VillanPower = "SuperStrength/Invulnerable",
                            Weaknesses = "None/Superman"
                        },
                        new
                        {
                            DcVillanId = 10,
                            CityLocation = "Star City",
                            PlacedInArkham = 0,
                            ThreatLevel = 4,
                            VillanAge = 40,
                            VillanName = "Professor Zoom",
                            VillanPower = "Reverse Speed Force",
                            Weaknesses = "None/Superman"
                        });
                });

            modelBuilder.Entity("SkillsShowcase.Shared.Domain.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "Devonpaniccia@gmail.com",
                            FirstName = "Devon",
                            Gender = 0,
                            LastName = "Rismay",
                            MaritalStatus = 0,
                            PhoneNumber = "8322156677"
                        });
                });

            modelBuilder.Entity("SkillsShowcase.Shared.Domain.Models.EmployeeSecretKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeSecretKeys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeName = "Devon Rismay",
                            SecretKey = "Auth-234252-rgsdfg4553-234dsdf-5555"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeName = "John Hull",
                            SecretKey = "Auth-234252-rgsdfg4553-234dsdf-5554"
                        },
                        new
                        {
                            Id = 3,
                            EmployeeName = "Quinshae Hopkins",
                            SecretKey = "Auth-234252-rgsdfg4553-234dsdf-5553"
                        },
                        new
                        {
                            Id = 4,
                            EmployeeName = "Robert Pyron",
                            SecretKey = "Auth-234252-rgsdfg4553-234dsdf-5552"
                        });
                });

            modelBuilder.Entity("SkillsShowcase.Shared.Domain.Models.Guitars", b =>
                {
                    b.Property<int>("GuitarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuitarId"));

                    b.Property<DateTime?>("BuildYear")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuitarManufacturer")
                        .HasColumnType("int");

                    b.Property<string>("GuitarModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("GuitarPrice")
                        .HasColumnType("float");

                    b.HasKey("GuitarId");

                    b.ToTable("Guitars");

                    b.HasData(
                        new
                        {
                            GuitarId = 1,
                            BuildYear = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuitarManufacturer = 1,
                            GuitarModel = "Custom Shop American Stratocaster",
                            GuitarPrice = 5000.2299999999996
                        },
                        new
                        {
                            GuitarId = 2,
                            BuildYear = new DateTime(2023, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuitarManufacturer = 1,
                            GuitarModel = "Custom Shop American Telecaster",
                            GuitarPrice = 4000.4499999999998
                        },
                        new
                        {
                            GuitarId = 3,
                            BuildYear = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuitarManufacturer = 1,
                            GuitarModel = "Special Edition Telecaster FMT HH",
                            GuitarPrice = 1000.55
                        },
                        new
                        {
                            GuitarId = 4,
                            BuildYear = new DateTime(2024, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuitarManufacturer = 1,
                            GuitarModel = "Acoustasonic Telecaster",
                            GuitarPrice = 1998.6300000000001
                        },
                        new
                        {
                            GuitarId = 5,
                            BuildYear = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuitarManufacturer = 2,
                            GuitarModel = "ES-339 Figured Semi-hollowbody",
                            GuitarPrice = 3500.8899999999999
                        },
                        new
                        {
                            GuitarId = 6,
                            BuildYear = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuitarManufacturer = 2,
                            GuitarModel = "SG Standard 61 Maestro Vibrola",
                            GuitarPrice = 2300.23
                        },
                        new
                        {
                            GuitarId = 7,
                            BuildYear = new DateTime(2020, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuitarManufacturer = 3,
                            GuitarModel = "Silver Sky",
                            GuitarPrice = 2749.23
                        },
                        new
                        {
                            GuitarId = 8,
                            BuildYear = new DateTime(2000, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuitarManufacturer = 4,
                            GuitarModel = "Artstar AS2000",
                            GuitarPrice = 2600.23
                        });
                });

            modelBuilder.Entity("SkillsShowcase.Shared.Domain.Models.SessionLogs", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionCountsPerDate")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionId");

                    b.ToTable("SessionLogs");

                    b.HasData(
                        new
                        {
                            SessionId = new Guid("92e289eb-8da5-4554-9d4d-65fbec329e9d"),
                            CreatedTime = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IpAddress = "01.6.0.20",
                            SessionCountsPerDate = 1,
                            UserAgent = "Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/127.0.0.0 Safari\\/537.36"
                        },
                        new
                        {
                            SessionId = new Guid("5c66c0d2-73f6-4af7-b5ba-5d3e964a3cfa"),
                            CreatedTime = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IpAddress = "02.6.0.20",
                            SessionCountsPerDate = 15,
                            UserAgent = "Safari\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/127.0.0.0 Safari\\/537.36"
                        },
                        new
                        {
                            SessionId = new Guid("5555319c-7df6-490d-8aa2-1edaa0bea797"),
                            CreatedTime = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IpAddress = "03.6.0.20",
                            SessionCountsPerDate = 30,
                            UserAgent = "FireFox\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/127.0.0.0 Safari\\/537.36"
                        },
                        new
                        {
                            SessionId = new Guid("8291f0fb-a1be-4056-bbae-0034840c1a2e"),
                            CreatedTime = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IpAddress = "04.6.0.20",
                            SessionCountsPerDate = 23,
                            UserAgent = "EnterExplorer\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/127.0.0.0 Safari\\/537.36"
                        },
                        new
                        {
                            SessionId = new Guid("61e97007-452d-4a0d-a107-cbf3f76fd8e9"),
                            CreatedTime = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IpAddress = "05.6.0.20",
                            SessionCountsPerDate = 43,
                            UserAgent = "Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/127.0.0.0 Safari\\/537.36"
                        },
                        new
                        {
                            SessionId = new Guid("0ee967b6-591e-4aff-83ce-a9ebf0a33de4"),
                            CreatedTime = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IpAddress = "06.6.0.20",
                            SessionCountsPerDate = 2,
                            UserAgent = "Windows\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/127.0.0.0 Safari\\/537.36"
                        },
                        new
                        {
                            SessionId = new Guid("677a43f3-48a2-4527-9e28-6547ff6f0637"),
                            CreatedTime = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IpAddress = "07.6.0.20",
                            SessionCountsPerDate = 6,
                            UserAgent = "Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/127.0.0.0 Safari\\/537.36"
                        },
                        new
                        {
                            SessionId = new Guid("684c1fab-5015-4457-b675-dc7d49a9bbf7"),
                            CreatedTime = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IpAddress = "08.6.0.20",
                            SessionCountsPerDate = 33,
                            UserAgent = "TechJuice\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/127.0.0.0 Safari\\/537.36"
                        },
                        new
                        {
                            SessionId = new Guid("9ce37660-95ff-4126-ad98-19e551fcf55a"),
                            CreatedTime = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IpAddress = "09.6.0.20",
                            SessionCountsPerDate = 20,
                            UserAgent = "TechJuice\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/127.0.0.0 Safari\\/537.36"
                        },
                        new
                        {
                            SessionId = new Guid("913a2029-7c2d-4e68-b9e0-455db4a62284"),
                            CreatedTime = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IpAddress = "10.6.0.20",
                            SessionCountsPerDate = 52,
                            UserAgent = "TechJuice\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/127.0.0.0 Safari\\/537.36"
                        },
                        new
                        {
                            SessionId = new Guid("8dd305c9-6ddf-406c-8558-0570597db647"),
                            CreatedTime = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IpAddress = "11.6.0.20",
                            SessionCountsPerDate = 10,
                            UserAgent = "Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/127.0.0.0 Safari\\/537.36"
                        },
                        new
                        {
                            SessionId = new Guid("3d8d9d50-658a-470d-8f23-88a775619c8d"),
                            CreatedTime = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IpAddress = "12.6.0.20",
                            SessionCountsPerDate = 49,
                            UserAgent = "Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/127.0.0.0 Safari\\/537.36"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
